releaseLabel: rgw-analysis-web

s3:
  configMapName: rgw-analysis-web-runtime
  secretName: rgw-analysis-web-s3
  inputKey: input/dataset.csv
  resultPrefix: results/rgw-analysis-web
  resultJsonKey: results/rgw-analysis-web/result.json
  resultIndexKey: results/rgw-analysis-web/index.html
  waitSeconds: 600
  pollIntervalSeconds: 5
  syncIntervalSeconds: 10

images:
  awsCli:
    repository: public.ecr.aws/aws-cli/aws-cli
    tag: "2.17.57"
    digest: sha256:603e86d34bbbba57bb1dfe1cc2ac5ef6eef0df1e0d0b953ee9b83a0f6cac3d59
    pullPolicy: IfNotPresent
  nginx:
    repository: nginx
    tag: "1.27.3-alpine"
    digest: sha256:814a8e88df978ade80e584cc5b333144b9372a8e3c98872d07137dbf3b44d0e4
    pullPolicy: IfNotPresent

resultWeb:
  replicas: 1
  service:
    type: ClusterIP
    annotations:
      scalex.io/exposure: internal
    port: 80
    targetPort: 8080

runtimeBinding:
  contractVersion: v1alpha1
  bindingType: rook-obc-s3
  sourceCluster: b
  sourceNamespace: scalex-rgw-analysis-web
  sourceClaimName: rgw-analysis-web-bucket
  sourceSecretName: rgw-analysis-web-bucket
  sourceConfigMapName: rgw-analysis-web-bucket
  targetNamespace: scalex-rgw-analysis-web
  targetSecretName: rgw-analysis-web-s3
  targetConfigMapName: rgw-analysis-web-runtime
  endpointUrl: http://10.33.142.10
  region: scalex-poc

placements:
  datasetSeeder: b
  analyzer: c
  resultWeb: b
  resultWebLoadBalancerIP: 10.33.142.20
  runtimeEndpointOnB: http://scalex-poc-rgw.csi-rook-ceph
