apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: scalex-federation
  namespace: argo
spec:
  description: ScaleX federated sandbox releases
  sourceRepos:
    - https://github.com/SmartX-Team/scalex-federation.git
    - https://github.com/SmartX-Team/scalex-*.git
  destinations:
    - name: scalex
      namespace: scalex-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: batch
      kind: Job
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: policy.karmada.io
      kind: OverridePolicy
    - group: policy.karmada.io
      kind: PropagationPolicy
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  orphanedResources:
    warn: true
