apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rgw-analysis-web-rgw
  namespace: scalex-cuty-rgw-analysis-web
  labels:
    app.kubernetes.io/part-of: rgw-analysis-web
    scalex.io/release: rgw-analysis-web
    scalex.io/component: runtime-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: scalex-cuty-rgw-analysis-web
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: scalex-cuty-rgw
  dataFrom:
    - extract:
        key: scalex/cuty/rgw-analysis-web/rgw
