apiVersion: scalex.io/v1alpha1
kind: FederationRelease
name: rgw-analysis-web
environment: cuty
namespace: scalex-cuty-rgw-analysis-web
renderer: helm/v1
source:
  repoURL: https://github.com/BellTigerLee/smurf-child.git
  path: charts/rgw-analysis-web
  revision: 05e2de4a0963a2373588a999c415e14b6648febc
values:
  path: releases/cuty/rgw-analysis-web/values.yaml
dependencies:
  path: releases/cuty/rgw-analysis-web/dependencies
policy:
  path: releases/cuty/rgw-analysis-web/karmada
promotion:
  mode: pinned
