apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: rgw-analysis-web-runtime-on-b
  namespace: scalex-rgw-analysis-web
spec:
  overriders: {}
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: rgw-analysis-web-runtime
      namespace: scalex-rgw-analysis-web
  overrideRules:
    - targetCluster:
        clusterNames:
          - b
      overriders:
        plaintext:
          - path: /data/S3_ENDPOINT_URL
            operator: replace
            value: http://scalex-poc-rgw.csi-rook-ceph.svc.cluster.local
