apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: rgw-analysis-web-object-bucket-claim-to-b
  namespace: scalex-rgw-analysis-web
spec:
  conflictResolution: Abort
  preemption: Never
  priority: 0
  propagateDeps: false
  schedulerName: default-scheduler
  resourceSelectors:
    - apiVersion: objectbucket.io/v1alpha1
      kind: ObjectBucketClaim
      name: rgw-analysis-web-bucket
      namespace: scalex-rgw-analysis-web
  placement:
    clusterAffinity:
      clusterNames:
        - b
