apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: rgw-analysis-web-runtime-credentials-to-b-c
  namespace: scalex-rgw-analysis-web
spec:
  conflictResolution: Abort
  preemption: Never
  priority: 0
  schedulerName: default-scheduler
  resourceSelectors:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      name: rgw-analysis-web-rgw
      namespace: scalex-rgw-analysis-web
  propagateDeps: false
  placement:
    clusterAffinity:
      clusterNames:
        - b
        - c
