apiVersion: scalex.io/v1alpha1
kind: ChildRepositoryEnrollmentList
repositories:
  - name: scalex-feature-poc
    repoURL: https://github.com/SJoon99/scalex-feature-poc.git
    paths:
      - chart
  - name: smurf-child
    repoURL: https://github.com/BellTigerLee/smurf-child.git
    paths:
      - charts/rgw-analysis-web
