apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: rgw-analysis-web-result-web-to-b
  namespace: scalex-rgw-analysis-web
spec:
  conflictResolution: Abort
  preemption: Never
  priority: 0
  schedulerName: default-scheduler
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: rgw-analysis-web-result-web
      namespace: scalex-rgw-analysis-web
    - apiVersion: v1
      kind: Service
      name: rgw-analysis-web-result-web
      namespace: scalex-rgw-analysis-web
  propagateDeps: true
  placement:
    clusterAffinity:
      clusterNames:
        - b
    spreadConstraints:
      - spreadByField: cluster
        minGroups: 1
        maxGroups: 1
